version: '3.8'

services:
  threat-db:
    image: postgres:17
    env_file:
      - ./backend/backend/.env
    volumes:
      - postgres_threat_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  threat-backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - threat-db

  threat-bot:
    build: ./bot
    depends_on:
      - threat-backend

  threat-frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - threat-backend

volumes:
  postgres_threat_data:
